### ISSUE TITLE
Update an already existing model/changeset

### ISSUE THREAD

**Issue by g8anusha** [poteto/ember-changeset#195]
Hi @poteto & others,

I am trying to have more than one validated-form in the page, for the same model, taking a changeset.
Different fields will be applicable for each form. But certain fields in one form, is a computed property of another form (the computed property is given in the model itself, so when we save / get, field is computed and received).

Since they are different forms, and each form creates a new model, the model is not updating the other form. Is there any way in which this can be achieved?

Please find this [Twiddle](https://ember-twiddle.com/b9f8fea705f4afbd5e4622040e7efc17?openFiles=templates.application.hbs%2C) for a similar demo.

Many thanks in advance!

**Comment by g8anusha** [comment]
Before model.save, the changes have all the field's value. When model.save is called, only the actually changed values are there. So, this cleans up the actual Ember Data model, and makes the other fields as empty.!!

**Comment by nucleartide** [comment]
Closing this since it's quite an old issue.

@g8anusha If you're still running into this problem though, you may want to open an issue downstream, in [ember-validated-form](https://github.com/adfinis-sygroup/ember-validated-form). Notice that if you log the following:

```hbs
{{log model.user.firstName}}
{{log model.user.lastName}}
```

The `firstName` and `lastName` above will log on save, while the `f.model.firstName` yielded by `validated-form` will not.
