### ISSUE TITLE
[Q] How to deal with relationships?

### ISSUE THREAD

**Issue by huberts** [poteto/ember-changeset#238]
Hello!

How can I use ember-changeset with complex models? My case is a hasMany() relationship where I would like to modify the list of child objects. The simplest example I could prepare is here:
[https://github.com/huberts/ember-changeset-test](https://github.com/huberts/ember-changeset-test)
When I try to add a child with changeset, there is an error on my array:
`this.get(...).addObject is not a function`
What is wrong in the example? Notice, that after fixing ember-changeset-validations on 1.2.8, this code works.

**Comment by nucleartide** [comment]
@huberts Thanks for the example! There are a couple of bugs with ember-changeset 1.4.0+ and ember-changeset-validations 1.2.9 right now, which is why you are seeing that error.

Pinning your ember-changeset-validations version to 1.2.8 is the right way to go for now.

We also currently don't support `hasMany`s. (I think https://github.com/poteto/ember-changeset/issues/118#issuecomment-254302025 still holds from a year ago.) It's on the roadmap though.

**Comment by huberts** [comment]
Thanks for your response! I will go with 1.2.8 then.

**Comment by snewcomer** [comment]
@huberts Would you mind trying out the latest master and lmk if you have any issues?  I think this might be fixed with the latest master.

**Comment by dguettler** [comment]
@snewcomer seems to still be an issue even when pinning to 1.6.0
Also somewhat related `Ember.get('changeset.hasManyRelation')` returns some ember-changeset object which doesn't support any array manipulation.
Versus `changset.get('hasManyRelation')` returns the e.g. ManyArray or whatever the relation is. Which is really a bit confusing especially when used in a template you get the former version.
So in order to iterate over entries in the relation you need to create a computed property which returns the result of the later.

**Comment by snewcomer** [comment]
Hm.  In regards to the second point, we are getting rid of that `relay` logic.  It is a mess right now.  Currently iterating on this below and hopefully will get a 2.0 out sometime in the next few months.  I'll try to evaluate this issue in 2.0.

https://github.com/poteto/ember-changeset/tree/2.0-beta

**Comment by muziejus** [comment]
I'm on 2.1.2, and I'm having a problem with relationships similar to OP's. My changeset (`entry`) has many `contributors`, and I'm trying to figure out how to ensure, on save, that the currently logged in contributor is one of the `contributors` that the `entry` has.

https://davidtang.io/2018/07/28/tracking-has-many-relationship-changes-with-ember-changeset.html looks like a usable solution, but it doesn't work for me. 

That is, when I do `changeset.get("contributors")`, it's 0 long, despite my looking at the database and seeing that it's _n_ long. Worse, on save, it saves an empty array. If I at least do `changeset.get("contributors").pushObject(this.currentContributor.contributor)`, then after save I'll have an array of length 1, but the previous contributors are all clobbered. 

Thanks.

**Comment by snewcomer** [comment]
There are specific ways to handle belongsTo and hasMany relationships in the new 3.0.0 series.  There should be some relevant tests showing how to handle relationships!

#380
