### ISSUE TITLE
RFC: Use es6 proxy

### ISSUE THREAD

**Issue by poteto** [poteto/ember-changeset#245]
Didn't have time to write up an actual RFC. Here's a quick [proof of concept](https://ember-twiddle.com/44e1aac8ed7ad53cd45c7419c655e77d?openFiles=controllers.application.js%2C) where we are just naively trapping `proxy.set` to validate prior to setting the value on the target object.

If we go down this route, we should implement that as a separate JS library and then have this addon consume that.

**Comment by krishandley** [comment]
That would be nice, my only question is what do we do about IE11?

**Comment by webark** [comment]
could this be something where we could base it off of the Proxy object, but fall back to a polyfill like https://github.com/GoogleChrome/proxy-polyfill

**Comment by nucleartide** [comment]
This is great 🙂  I think we could continue the bug-fixing efforts with nested keys and get a release out, then focus on integrating validated-proxy? It'll be easier since we'll already have defined nested keys behavior.

**Comment by poteto** [comment]
This isn't a mandate by any means, I'm using `validated-proxy` as an experiment. I wouldn't change any plans yet! That said, I wanted to start a discussion and I will soon add a real RFC into my first comment

**Comment by nucleartide** [comment]
Having looked through validated-proxy a bit more, I think it’d be interesting to explore use cases. An obvious one is using validated-proxy with Redux, where you’d emit actions only when data is valid. Since we’re not coupled to Ember anymore, maybe an Express middleware for validated-proxy would be useful too. I’m curious what people have used Ecto.Changeset for, since all those use cases would apply here.

As an aside, one of my goals is to capture UI use cases in ember-changeset’s wiki going forward.

Implementation-wise, I’m all for having ember-changeset consume validated-proxy. We’d still need some Ember-specific stuff like relays, but it’d definitely clean up the code. Not to mention the TypeScript typings look really nice.

**Comment by sandstrom** [comment]
This sounds awesome! Would this help with the issues around 'deep set'?

Proxy seems to have great browser support :https://caniuse.com/#search=proxy

IE 11 is quickly on its way out:
https://support.zendesk.com/hc/en-us/articles/360002084367-Removal-of-support-for-Internet-Explorer-11
https://blog.developer.atlassian.com/retiring-ie11-support-for-atlassian-cloud-server-and-data-center-products/

Something "opt-in" that companies with min browser requirements > IE 11 could use would be lovely 😄
