### ISSUE TITLE
Changeset should work with Ember Data model refreshes

### ISSUE THREAD

**Issue by nucleartide** [poteto/ember-changeset#253]
See https://github.com/poteto/ember-changeset/pull/241#discussion_r156409018.

**Comment by allthesignals** [comment]
Bit by this! Ouch!

Instinctively, I looked for a changeset method that reset it's state to the refreshed version of the model it wrapped.

Unsure of how to proceed but will report back if I find anything.

**Comment by snewcomer** [comment]
@allthesignals What is your use case?  Similar to the linked PR?  And `rollback` doesn't work for your use case?

**Comment by allthesignals** [comment]
@snewcomer yep, similar to the linked PR. I am dealing with file uploads:

1. require at least 1 upload (validate length of an array)
2. push files to upload, save()/[reload](https://api.emberjs.com/ember-data/3.10/classes/DS.Model/methods?anchor=reload)()

My workaround right now is replace the array property on the changeset with a new array. But this won't catch upload failures which is Bad.

> And `rollback` doesn't work for your use case?

Unless I'm misunderstanding, no: 
![image](https://user-images.githubusercontent.com/5004319/90554601-214e9a00-e164-11ea-9582-e5993d2fabf3.png)

If I rollback, it's still invalid — this is because it may initialize from an already-invalid underlying object. It doesn't seem to pick up the newly save'd()/reload'ed() model.

**Comment by snewcomer** [comment]
So what you want is something like `reset state`?  Effectively clear `changes` && `content`.

**Comment by allthesignals** [comment]
> So what you want is something like `reset state`? Effectively clear `changes` && `content`.

Exactly :) 

I think the design problem comes from the nature of Ember Data and JSON:API. On subsequent interactions with the API, if the underlying model changes via a `reload`, those changes are implicitly circumventing the changeset. So, for example, this could put the underlying model in a valid state, but changeset won't know because it doesn't know that the underlying model has changed through some other means (the Ember Data adapter).

**Comment by snewcomer** [comment]
And looking at alternative solutions, what are the downsides of just `new Changeset` after `save`?  Is there still state you want from the old one?

**Comment by allthesignals** [comment]
> And looking at alternative solutions, what are the downsides of just `new Changeset` after `save`? Is there still state you want from the old one?

Nope, there isn't, but the way I've [set up my changesets](https://github.com/NYCPlanning/labs-applicant-portal/blob/develop/client/app/components/saveable-form/validator.js) gives me some interesting double-render errors.

I'll try it again so I can provide more details.

**Comment by snewcomer** [comment]
Interesting.  I could see something like `restore` but for clearing state + setting CONTENT to the original model (in a new state I assume after save).

**Comment by jkeen** [comment]
Also running into this -- is this a recent change in behavior? I'm on the latest version of ember + changeset and I don't remember running into this before?

But anyhow: I'm saving a changeset, the request errors, and despite restoring to a shapshot pre-save attempt, the underlying model still shows the failed changes. I want to restore the model back to the way it was

**Comment by snewcomer** [comment]
@jkeen I'll see if I can write a failing test for your problem and go from there!

**Comment by snewcomer** [comment]
Here is some work to set previous values on model after save error.  Let me know what you think!

https://github.com/validated-changeset/validated-changeset/pull/80

**Comment by nucleartide** [comment]
Hello 👋 closing this since I'm getting notified, sorry! 😬 

If it's okay, please open another issue? 🙏

**Comment by snewcomer** [comment]
@allthesignals Mind putting up an issue that is not covered by 3.9.0?  I'll get to it this weekend!

**Comment by jkeen** [comment]
This is great, thanks @snewcomer!
