### ISSUE TITLE
Issue with Moment data while saving

### ISSUE THREAD

**Issue by nandorstanko** [poteto/ember-changeset#277]
## Version
1.4.2-beta.0

## Steps to reproduce
I'm using Moment as a DS datatype (with custom transform). Getter and setter are working fine. The issue is that when I'm trying to save the changeset, the Moment data is not getting set into my model. I think that the problem is somewhere in the execute function. The changedKeys object contains hundreds of keys (like this one: dob._isAMomentObject), but changes contains only the "dob" key.

`if (!changedKeys.includes(key)) {
    (0, _emberDeepSet.default)(content, key, get(resetProperties, key));
}`

**Comment by nucleartide** [comment]
@nandorstanko Thanks for opening the issue. I believe you aren't on 1.4.2-beta.0, since the `if (!changedKeys.includes(key))` line doesn't exist in the codebase anymore.

Have you updated your version of ember-changeset-validations? When inspecting the addon, the `index.js` file for `ember-changeset` should look something like [this](https://github.com/poteto/ember-changeset/blob/master/addon/index.js).

**Comment by nandorstanko** [comment]
@nucleartide Thanks for the reply! I thought that I was on that version, because I am on that version, but sadly ember-changeset-cp-validations is not... This was tricky, learned from it. Sorry for the false alarm!
