### ISSUE TITLE
Add examples (contributors welcome!)

### ISSUE THREAD

**Issue by nucleartide** [poteto/ember-changeset#284]
This ties into #171 – we should start building more examples in the vein of @poteto's original [Twiddle](http://bit.ly/ember-changeset-demo). It might just be me, but maintaining this addon without using it in a project feels somewhat pointless and demotivating.

As a future direction, I'd like to focus on how `ember-changeset` enables certain [form UX patterns](https://www.google.com/search?q=beautiful+form+UI). Of course, the big UX pattern is validation, but there are definitely other patterns out there. For example, issue #69 suggests undo/redo, which is another UX pattern to think about – whether one uses Redux or not.

Thinking about UX principles is more interesting to me, and also has more longevity than specific frameworks/libraries/addons.

**Comment by lougreenwood** [comment]
I implemented a simple `changeset-store` service recently - this allows me to re-use the same form component in multiple places, but have each instance of the component share the same changes for a given model.

It allows for forms in modals and 'hide' behaviour where a user may make a change to a form, hid the form to go get some other info then re-open for the form on some other page.

Usually, because component state is destroyed with components, the changes would be lost, but my store-service handles this....

Maybe this is a UX pattern you'd find interesting?

**Comment by snewcomer** [comment]
Looking to create generic examples with validated-changeset!
