### ISSUE TITLE
changeset.rollback works the first time only

### ISSUE THREAD

**Issue by Mithrilhall** [poteto/ember-changeset#294]
I threw together a sample project for testing nested keys and noticed an issue with the rollback method.

## Version
1.5.0-beta.0

## Test Case
https://github.com/Mithrilhall/changeset-test-nested.git

## Steps to reproduce
```
yarn install
ember s
```

## Expected Behavior
Clicking the **restore** button should rollback all values.
## Actual Behavior
The **restore/rollback** button should rollback changeset and appears to work fine on nested keys the first time. Additional attempts to rollback (clicking on the button) do not appear to rollback the nested values.

**Comment by bentesha** [comment]
@Mithrilhall the `rollback()` method does not define any parameters. You should use the `restore()` method instead, and pass in the snapshot object.

However, both `restore()` and `rollback()` methods, when correctly used, do seem to work only with the first click. Any further changes are not being restored. This is possibly a bug

**Comment by Mithrilhall** [comment]
@bentesha I tried doing a _changeset.restore(this.snapshot);_ and I never get my original values back; but it does clear the errors.

_changeset.rollback()_ clears the errors and restores my values but only the first time for nested values.

**Comment by bentesha** [comment]
@Mithrilhall Yes, `changeset.rollback()` only works for the first time. As this only happens with nested properties, there is a good chance that this is a bug. I will try to look into the code and see if I can find anything.

**Comment by bentesha** [comment]
@Mithrilhall I added a few extra tests to check if this is a bug, and it turned out that your issue has to do with how ember works (unfortunately, I don't have enough Ember knowledge to explain this behaviour).

The underlying changeset object is actually mutated in both scenarios, before and after `rollback()` gets called. You can verify this using Ember Inspector. However, for some reasons, the state of the changeset object is not reflected on the UI. (It gets out of sync after the `rollback()` call)

Once `rollback()` is called, any further changes to the changeset object won't be reflected on the UI.

**Comment by Mithrilhall** [comment]
Could one of you mark this as a bug (@nucleartide or @poteto)?

**Comment by snewcomer** [comment]
@Mithrilhall Thx for the reproduction!  I just put up #310.  One of the tests is that rollback twice works.  There more to add here, but thought we would start there.  I think there is some more assertions to add to fully reproduce your case.

**Comment by snewcomer** [comment]
I'll close this for now.  I believe this should work in 2.2.4 or the new 3.0 series!  Thank you for the issue!
