### ISSUE TITLE
Saving a changeset does not save nested models

### ISSUE THREAD

**Issue by nickschot** [poteto/ember-changeset#331]
## Test Case

\-

## Steps to reproduce

When providing a changeset with nested models, the nested model is never saved. Changes on it are detected properly (in the changes array).

## Expected Behavior

Dirty tracking should work properly and save should be called on all models with changes.

## Actual Behavior

 - The `isDirty` flag is not updating (even though the changes array is).
 - Save is never called on sub-models when calling `changeset.save()`.

Note: Putting this here to keep track of it. We should take a look at it after the 2.x updates have been merged.

**Comment by nickschot** [comment]
Will do tomorrow!

**Comment by nickschot** [comment]
Thanks for pinging me. Below are some initial findings:

- emptying a belongsTo (to null) now correctly clears the value and is detected as a valid change
- Setting a value on a related model is not detected as a change (e.g. model user with a relationship to a post. Make a changeset of the user, have a form with value `post.title`)
- As it is not detected as a change a save is also not triggered on the nested model (as raised in this issue).

Let me know what the intended behaviour is on these cases.

**Comment by snewcomer** [comment]
@nickschot What does your logic look like?  Does it involve `mut` helper?  If so, perhaps this is related to a recent change we made.  I believe a nested set will add a `CHANGE`, but if using `set(changeset, ...)` then it won't since we override `changeset.set`.  Created a `changeset-set` template helper for this reason.  Although doesn't work completely as expected b/c it isn't propagating those changes back to the template (think I am missing some notifyProperyChange logic or something). 

 Lmk what you think!

https://github.com/poteto/ember-changeset/pull/335/files#diff-f721c38c4110379388cab513565fec56R346

**Comment by nickschot** [comment]
Ugh, I knew I forgot something, we even talked about that in the Discord. Ember-bootstrap uses the set indeed. I'm gonna override that and test again. I can come back to you on this next Tuesday.

**Comment by nickschot** [comment]
@snewcomer it does indeed correctly identify and set changes on nested models when using `changeset.set(.....)`. The main issue is still valid, no `.save()` is called on the nested models.

**Comment by afinne** [comment]
Can confirm, changes are applied, but `.save()` is not called on nested models.

**Comment by snewcomer** [comment]
@afinne what does the shape of this object with nested models look like?  Seems like this is more common than I think.  I can write a test and see if solvable if you have an example to share!

**Comment by snewcomer** [comment]
In the 3.0 series, `save` will only be called on top level objects!
