### ISSUE TITLE
Is there a way to execute() only after save() resolves?

### ISSUE THREAD

**Issue by axsuul** [poteto/ember-changeset#458]
This feels like a common use case so I'm wondering if this is already possible within this library. 

I'd like it so that the underlying model is not changed until the `Promise` returned from `save()` resolves. Currently, the data will propagate right away throughout the template as soon as `save()` is executed even though the `Promise` is still in progress. This is a nitpick with user experience. For example, a modal is open and it's waiting to be closed as soon as the `Promise` resolves but the data has already propagated to the model which creates a disconnect in the UX.

Any suggestions or workarounds?

**Comment by snewcomer** [comment]
https://github.com/validated-changeset/validated-changeset/blob/master/src/index.ts#L334

Great idea!  I think this makes technical sense.  What do you think about this in `validated-changeset`?

```js
try {
  const result = await savePromise;
  this.execute();
catch (e) {
  // noop
}
```

**Comment by axsuul** [comment]
@snewcomer Thanks for chiming in! 

Hmm I'm not sure if that will get us there since in your proposal, `savePromise` would be called on the model when it doesn't have changes yet. Somehow the model needs to be cloned so that a separate changeset can be called on the cloned model. Then when the cloned model saves, we transfer over the changes... or am I thinking about this wrong?

**Comment by snewcomer** [comment]
@axsuul You are right.  This is a tough issue.  I forgot we need to apply the underlying changes before saving the underlying content.  

Note we do have 
- `snapshot` - https://github.com/validated-changeset/validated-changeset/blob/e6823b089cf1edaf47fa2297aa9e372b225cbb70/src/index.ts#L553

That might be of use to you.  Although I'm not exactly sure how.

Cloning on our end would be tough because of the various end user shapes of objects.  

I guess what I would suggest is you clone your model, pass the clone to `Changeset` and when the save promise is done, set the old model to the new model.

If you happen to come up with a solution we can integrate into the library, I'm all ears!!

**Comment by jkeen** [comment]
@axsuul Did you ever figure out an easy way to do this? This does seem like a common and useful thing and from my messing with it, it seems like there are a number of hoops that need to be jumped through in order to make this work now.

I tried getting what @snewcomer suggested working but didn't quite get there

**Comment by snewcomer** [comment]
Overall, I think we would be getting ourselves in trouble if we tried to clone the object.  If we were just dealing with plain objects, it would be easy.  But given the varied types of data structures (including proxies && ember-data relationships), we certainly would get it wrong.  What do you think?

**Comment by jkeen** [comment]
yeah, I hear that.

To illustrate the specific problem a little better: my app has models that are either 'published' or 'draft', and when a model changes states it animates between different areas on the page (using `ember-animated`). With the current `save()` behavior the model gets changed (`execute()`), the animation gets triggered, the request gets fired, and then if the the request errors out the item remains in the wrong section. 

#253 would send the item back to the correct section, but still not solve the whole problem.

The closest I came to mapping out a `save({execute:false})` slash `saveThenExecute` type method is something like this:
```javascript

// App Code ---
let changeset = new Changeset(model, lookupValidator(ModelValidations), ModelValidations)
changeset.set('published', true) 
changeset.save({execute: false}).then(response => changeset.execute())
// ----------------

// ember-changeset imaginary code ---------

function saveWithoutExecute() {
  let modelName = model.constructor.modelName;
  let adapter = model.store.adapterFor(modelName);
  let type = 'PATCH' // TODO: determine this
  let url = adapter.buildURL(modelName, model.id, model.serialize({includeId: true}), type)

  var data = {}
  if (changeset.isValid) {

    // here's the trouble spot -------------------------------------------------
    var mergedData = mergeDeep(changeset._content, changeset._changes);
    // ------------------------------------------------------------------------

    data = mergedData.serialize({includeId: true})
    let ajaxOptions = adapter.ajaxOptions(url, type, {}) // get adapter ajax options if present
    return adapter.ajax(url, type, Object.assign((ajaxOptions || {}), { 
      headers: adapter.headers, // get authenticated headers if present
      data: data
    }))
  }
}
```

The marked line is basically what `execute` is doing and this needs to be done in order to get the correct payload serialization, but unfortunately the `mergeDeep` function mutates `changeset._content`, which changes the underlying model causing the exact problem I'm trying to avoid. I tried using `ember-copy` to deepCopy the `changeset._content`, but it doesn't implement Copyable so that didn't work. Not sure where to go from here.

It would be great if changeset.serialize() serialized the current changeset _with_ changes, but currently it just serializes the model underneath it. I think this is a valid usecase that'd be nice, but maybe it's not an `ember-changeset` thing? Maybe `ember-changeset` doesn't want to get into the business of sussing out request details and this whole thing is more of an `ember-data` problem? 

What do you think, @snewcomer?

**Comment by snewcomer** [comment]
Given the request layer for any given object can be just a plain function that accepts a hash of data; or an ember-data model that relies on associated internal state of the model to make the request, it seems the only way to make this reliably work is to allow you to extend the Changeset and implement your own `save` function.  I'd be open to an inherent solution to this library...

https://github.com/poteto/ember-changeset#extending-the-base-ember-changeset-class
