### ISSUE TITLE
IE11 support?

### ISSUE THREAD

**Issue by andreyfel** [poteto/ember-changeset#491]
I haven't tested this but apparently this addon doesn't support IE11 since it uses `Proxy`.
Should it be documented?

**Comment by Kilowhisky** [comment]
Sorry to dig up an old thread but....

Is proxy the only breaking change for IE11? Wouldn't a documented polyfill just be all that is needed?
With loss of IE 11 support this library now doesn't track with ember since ember still supports IE 11. Its a blocker for adoption by some people.

My application requires IE 11 support and currently uses `ember-cp-validations` which appears to be deprecated and doesn't work with octane. This library has been a suggested replacement but this blocks my ability to use it.

**Comment by snewcomer** [comment]
@Kilowhisky You can try v2 (2.2.4) and see if that works for your application!
